packages:
  - apps/*
  - packages/*

autoInstallPeers: true
strictPeerDependencies: false
sharedWorkspaceLockfile: true
confirmModulesPurge: false
minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200

allowBuilds:
  electron: true
  electron-builder: true
  electron-winstaller: true
  esbuild: true
  msw: true

overrides:
  js-yaml@>=4.0.0 <4.3.1: ^4.3.1
  fast-uri@>=3.0.0 <3.1.6: 3.1.6
  qs@>=2.2.5 <6.16.0: 6.16.0
  '@xmldom/xmldom@>=0.7.0 <0.8.15': 0.8.15
