/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 741a98ec536a9170a965f03f5c849113)
interface __BaseEnv_Env {
  ASSETS: Fetcher;
  PUBLIC_ORIGIN: 'https://outreachr.eliza.app';
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
